-d D:\Python_Project\TangNano-9K-example\spi_lcd\impl\gwsynthesis\lcd114_test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\Python_Project\TangNano-9K-example\spi_lcd\src\lcd114_test.cst
-cfg D:\Python_Project\TangNano-9K-example\spi_lcd\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
